### ISSUE TITLE
compiling .pyc files failure on C++ project

### ISSUE THREAD

**Issue by scopatz** [conda/conda-build#1167]
[My Cyclus recipe](https://github.com/conda-forge/staged-recipes/pull/678) was working locally a last week but now it seems like conda build attempts to byte compile Python code that doesn't exist.  This is a C++ project that happens to use some Python in its build system and installs a single-file, stand-alone python script that is installed by CMake. 

There is nothing for conda to byte compile so it shouldn't attempt this. The traceback is here:

```
compiling .pyc files...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/scopatz/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/home/scopatz/miniconda/lib/python3.5/site-packages/conda_build/main_build.py", line 151, in main
    args_func(args, p)
  File "/home/scopatz/miniconda/lib/python3.5/site-packages/conda_build/main_build.py", line 414, in args_func
    args.func(args, p)
  File "/home/scopatz/miniconda/lib/python3.5/site-packages/conda_build/main_build.py", line 357, in execute
    debug=args.debug)
  File "/home/scopatz/miniconda/lib/python3.5/site-packages/conda_build/build.py", line 632, in build
    preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "/home/scopatz/miniconda/lib/python3.5/site-packages/conda_build/post.py", line 182, in post_process
    compile_missing_pyc(files)
  File "/home/scopatz/miniconda/lib/python3.5/site-packages/conda_build/post.py", line 174, in compile_missing_pyc
    call([python_exe, '-Wi', '-m', 'py_compile'] + compile_files, cwd=cwd)
  File "/home/scopatz/miniconda/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/scopatz/miniconda/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/home/scopatz/miniconda/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/scopatz/miniconda/envs/_build'
```

And my conda info is:

```
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.9
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /home/scopatz/miniconda  (writable)
  default environment : /home/scopatz/miniconda
     envs directories : /home/scopatz/miniconda/envs
        package cache : /home/scopatz/miniconda/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/conda-forge/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/scopatz/.condarc
         offline mode : False
    is foreign system : False
```

Since this is a 10 - 30 min build, it is very sad whenever it breaks.

**Comment by scopatz** [comment]
Note, in addition to my local break on linux, here is a conda-forge break on mac: https://travis-ci.org/conda-forge/staged-recipes/jobs/149277660#L2432

**Comment by ocefpaf** [comment]
Another project with the same failure to provide another data point:

https://github.com/conda-forge/staged-recipes/pull/582#issuecomment-236981508

**Comment by msarahan** [comment]
There is one dumb mistake that @mingwandroid fixed in #1163 - might this be related, or is it something else completely?

@scopatz - just confirming, this shows up locally - is this in the context of conda-build-all, or using only conda-build?  Just trying to narrow down places to look.

**Comment by scopatz** [comment]
@msarahan Yes, this seems like the error.  And yes, this occurs both locally (which I verified on linux) and on conda-forge (which failed on mac).  Thanks for the speedy response.

**Comment by scopatz** [comment]
On the current 1.21.x branch (ed323c1ae2997f32731c1518ca9b85399887c49c), I am still seeing this error:

```
compiling .pyc files...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/scopatz/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/home/scopatz/.local/lib/python3.5/site-packages/conda_build-1.21.9+12.ged323c1-py3.5.egg/conda_build/main_build.py", line 152, in main
    args_func(args, p)
  File "/home/scopatz/.local/lib/python3.5/site-packages/conda_build-1.21.9+12.ged323c1-py3.5.egg/conda_build/main_build.py", line 415, in args_func
    args.func(args, p)
  File "/home/scopatz/.local/lib/python3.5/site-packages/conda_build-1.21.9+12.ged323c1-py3.5.egg/conda_build/main_build.py", line 358, in execute
    debug=args.debug)
  File "/home/scopatz/.local/lib/python3.5/site-packages/conda_build-1.21.9+12.ged323c1-py3.5.egg/conda_build/build.py", line 646, in build
    preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "/home/scopatz/.local/lib/python3.5/site-packages/conda_build-1.21.9+12.ged323c1-py3.5.egg/conda_build/post.py", line 182, in post_process
    compile_missing_pyc(files)
  File "/home/scopatz/.local/lib/python3.5/site-packages/conda_build-1.21.9+12.ged323c1-py3.5.egg/conda_build/post.py", line 174, in compile_missing_pyc
    call([python_exe, '-Wi', '-m', 'py_compile'] + compile_files, cwd=cwd)
  File "/home/scopatz/miniconda/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/scopatz/miniconda/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/home/scopatz/miniconda/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/scopatz/miniconda/envs/_build'
```

**Comment by jakirkham** [comment]
> just confirming, this shows up locally - is this in the context of conda-build-all, or using only conda-build? Just trying to narrow down places to look.

Was wondering the same question earlier. This can be demonstrated to be `conda-build` only. Please see this issue ( https://github.com/conda-forge/obspy-feedstock/issues/1 ) for details.

**Comment by msarahan** [comment]
obspy works for me on Mac/py3.5 with conda-build's current 1.21.x branch.  I have very limited internet right now - on a metered connection - and can't download enough to test on my linux docker machine.  I would appreciate it if anyone else could try this on the current 1.21.x code.  I am planning a 1.21.11 release when this is resolved.

**Comment by megies** [comment]
> obspy works for me on Mac/py3.5 with conda-build's current 1.21.x branch. I have very limited internet right now - on a metered connection - and can't download enough to test on my linux docker machine. I would appreciate it if anyone else could try this on the current 1.21.x code. I am planning a 1.21.11 release when this is resolved.

@msarahan looks like current 1.21.x is building ObsPy just fine: conda-forge/obspy-feedstock#3

**Comment by msarahan** [comment]
pyc compilation issues should be much better now (1.21.14).  There was a bug where removal of the egg directory was happening before compilation, leading compilation to look for files that were not there.

Closing this issue for now.  Please reopen or open a new issue if you still have problems.
