### ISSUE TITLE
conda-skeleton cannot jump start packages using `cythonize` in `setup.py`

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda-build#1697]
conda-skeleton fails with an ImportError on Cython, if setup.py imports cythonize to build Cython Extensions.

This is because, `get_requirements` will try to run setup.py with an environment that doesn't have cython installed. 

cython is just a commonly used case. The setup.py of my packages needs mpi4py in order to find the mpicc compilers. There shall be a way to notify conda-skeleton about these packages -- as an commandline argument?

**Comment by msarahan** [comment]
@rainwoodman is this fixed by #1698?  Can I close this issue?

**Comment by rainwoodman** [comment]
Yes it is. May want to document this flag somewhere though.

Y

**Comment by kheuton** [comment]
I'm still having a trouble even after [#1698](https://github.com/conda/conda-build/pull/1698), but maybe it's a slightly different issue.

I was able to successfully use the `--extra-specs` flag to use `conda skeleton` to create a recipe for my package that required Cython, but when attempting to `conda build` that recipe, it fails again with `ImportError: No module named Cython.Distutils`.

I guess there's a few options here:

1. Make the `--extra-specs` flag add the extra dependencies to the recipe's build requirements
2. Add an `--extra-specs` flag to `conda build`
3. Edit the recipe by hand

Or is this problem avoidable by some other route I'm not seeing?

**Comment by rainwoodman** [comment]
Did you declare cython in your install_requirements?

**Comment by kheuton** [comment]
What's install_requirements? I'm using `conda skeleton` to build a recipe from someone else's pypi package. I was able to successfully use `conda skeleton` with `--extra-specs cython`, but then `conda build` failed until I went into the `meta.yaml` created by conda-skeleton and added cython to the build requirements

**Comment by rainwoodman** [comment]
I thought a proper setup.py shall declare the packages required for
building in install_requirements argument of the call to setup.

Does the package install from pip when cython is not present?

Yu

On Mar 10, 2017 10:36 AM, "kheuton" <notifications@github.com> wrote:

What's install_requirements? I'm using conda skeleton to build a recipe
from someone else's pypi package. I was able to successfully use conda
skeleton with --extra-specs cython, but then conda build failed until I
went into the meta.yaml created by conda-skeleton and added cython to the
build requirements

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/conda/conda-build/issues/1697#issuecomment-285748996>,
or mute the thread

**Comment by rainwoodman** [comment]
The name is 'install_requires'. skeleton produces a buildable recipe for this package:

https://github.com/rainwoodman/kdcount/blob/master/setup.py#L40

Could you post a link to the setup.py of the package?

**Comment by kheuton** [comment]
Hmm, strange. `pip install` does seem to work even in environments without Cython, and Cython is not listed in the [setup.py](https://github.com/scikit-sparse/scikit-sparse/blob/v0.2/setup.py)'s install_requires
[I know i'm using a super old version of the scikit-sparse library]

**Comment by rainwoodman** [comment]
pip worked fine for newer version of scikit-sparse because it come with a setup.cfg. The old version doesn't exist on pypi. I tried and it failed with Cython not found error with v0.2.zip.

My current definition --extra-specs only covers bootstrapping of setup.py for extracting package meta-data; thus they do not mix into the generated recipe. Maybe we want to change that -- but I feel your approach 3 may be the most flexible for very legacy packages.

**Comment by kheuton** [comment]
Sounds like a good plan, I guess my problems are just a quirk of this legacy code

And `scikits.sparse` v0.2 is on pypi, but it has a different name than the newer `scikit-sparse`. It seems the package was a bit disorganized then, even the version `0.2` release is tagged as version `0.1`.

Here's the link to the pypi legacy version I was able to pip install even without Cython: https://pypi.python.org/packages/8c/02/2bb86c30bd40d36d529cbe9674c7e092ca527c696056966c1cfa8086fdfb/scikits.sparse-0.2.tar.gz#md5=0ee93ef2b1e5b9eb5c2a4e29dd06168a

**Comment by rainwoodman** [comment]
Sure.

Here is what I get:

```
(testscikit) [yfeng1@waterfall tmp]$ pip install https://pypi.python.org/packages/8c/02/2bb86c30bd40d36d529cbe9674c7e092ca527c696056966c1cfa8086fdfb/scikits.sparse-0.2.tar.gz#md5=0ee93ef2b1e5b9eb5c2a4e29dd06168a
Collecting https://pypi.python.org/packages/8c/02/2bb86c30bd40d36d529cbe9674c7e092ca527c696056966c1cfa8086fdfb/scikits.sparse-0.2.tar.gz#md5=0ee93ef2b1e5b9eb5c2a4e29dd06168a
  Downloading scikits.sparse-0.2.tar.gz (204kB)
    100% |████████████████████████████████| 204kB 2.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-bf7gLA-build/setup.py", line 38, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-bf7gLA-build
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by msarahan** [comment]
Better error message added for this situation in #2784 - that's probably the best we can do.  Closing.
