### ISSUE TITLE
Building a noarch package for navigator is resulting in incorrect entry points on windows

### ISSUE THREAD

**Issue by goanpeca** [conda/conda-build#1786]
@msarahan  
For internal QA testing, I am creating noarch packages (old style) by running

[This recipe](https://github.com/ContinuumIO/navigator/tree/master/conda.recipe)

And the following command on OSX:
```
$ PRERELEASE=True conda build conda.recipe/

...
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /Users/gpena-castellanos/anaconda/conda-bld/osx-64/anaconda-navigator-1.5rc1-py_4.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []

```

When trying to install this package on windows (any version)

```
(C:\Users\builder\Anaconda3) C:\Users>conda install anaconda-navigator -c contin
uumcrew -f
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment C:\Users\builder\Anaconda3:

The following NEW packages will be INSTALLED:

    anaconda-navigator: 1.5rc1-py_4 continuumcrew

Proceed ([y]/n)? y

anaconda-navig 100% |###############################| Time: 0:00:04   1.09 MB/s
C:\Users\builder\Anaconda3\lib\site-packages\conda\core\link.py:471: UserWarning
: Package continuumcrew::anaconda-navigator-1.5rc1-py_4 uses a pre-link script.
Pre-link scripts are potentially dangerous.
This is because pre-link scripts have the ability to change the package contents
 in the
package cache, and therefore modify the underlying files for already-created con
da
environments.  Future versions of conda may deprecate and ignore pre-link script
s.

  """) % dist)

```

And then trying to run `anaconda-navigator` results in:

```
(C:\Users\builder\Anaconda3) C:\Users>anaconda-navigator
failed to create process.
```

Using latest `conda-build` and `conda`

**Comment by msarahan** [comment]
This entry point script runs fine for me if I do:

```
pythonw.exe c:\miniconda2\scripts\anaconda-navigator-script.py
```

I'm not clear that there is a way to specify to conda-build that the script needs to be run with pythonw, though.  There needs to be, for sure.  The different between python and pythonw is described at http://stackoverflow.com/a/30313091/1170370

I need to talk with @ilanschnell tomorrow to see how this is supposed to work.

**Comment by msarahan** [comment]
Sorry, that's not actually the issue.  Running python.exe on that python script also works fine.  It's an issue with the executable that is meant to launch the script.  I'll debug it tomorrow.

**Comment by msarahan** [comment]
The bug appears to be a lack of prefix replacement occurring in the anaconda-navigator-script.py file.  If I manually edit that file and change:

```
#!/opt/anaconda1anaconda2anaconda3/bin/python
```

to match my python installation location:

```
#!C:\miniconda2\python.exe
```

then anaconda-navigator.exe launches just fine.  This might be both a conda and a conda-build fix.

**Comment by msarahan** [comment]
fixed by #1806 and https://github.com/conda/conda/pull/4828 - closing.

**Comment by wsfax** [comment]
@msarahan I still see the problem with the latest conda-build (2.1.9) and the latest conda (4.3.17) on windows python 2.7
