### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by neok-m4700** [conda/conda-build#2104]
there are leftovers when using build.build_tree

config.clean() is not cleaning up, because metadata.config is a different object

here is a proposed patch, https://github.com/neok-m4700/conda-build/commit/59eb267ecb8a95d9e93846d9b94ef9c563c2bf28

but I haven't tested if it is safe enough.

**Comment by msarahan** [comment]
Is this fixed by #2100?

**Comment by neok-m4700** [comment]
I've tested the patch and it does not fix my issue.

(on conda-build=3.0.0, only neok-m4700/conda-build@59eb267 fixes it, i.e. proper cleanup)

this is my configuration :
```python
config = dict(
    dirty=False,
    debug=False,
    verbose=True,
    disable_pip=False,
    remove_work_dir=True,
    anaconda_upload=False,
    filename_hashing=False,
    override_channels=True,
    no_download_source=True,
    ignore_system_variants=True,
)
```

**Comment by msarahan** [comment]
Thanks for the confirmation.  I'll try to work your patch in and fix the stragglers.
