### ISSUE TITLE
skip-existing still doesn't skip existing packages in 3.0.4

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#2187]
After updating to 3.0.4 the crash documented in #2172 is fixed. Unfortunately the build is still not skipping existing packages, it just starts to build.. that functionality worked fine in 2.1.17.

**Comment by msarahan** [comment]
We do have tests for this, but you're hitting a path that seems like some
parts of a package are built, but others are not. Can you post a minimal
reproducing recipe?

**Comment by gabm** [comment]
well its as easy as:

```
package:
  name: "testpkg"
  version: "1.0.0"
```

just build it twice with skip existing... in conda 3.0.4 it says:

```
$ conda build . --skip-existing
source tree in: /home/gabm/miniconda3/conda-bld/testpkg_1499864529470/work
Attempting to finalize metadata for testpkg
INFO:conda_build.metadata:Attempting to finalize metadata for testpkg
BUILD START: ['testpkg-1.0.0-hbf21a9e_0.tar.bz2']
Packaging testpkg
INFO:conda_build.build:Packaging testpkg
Packaging testpkg-1.0.0-hbf21a9e_0
INFO:conda_build.build:Packaging testpkg-1.0.0-hbf21a9e_0
number of files: 0
Fixing permissions
Fixing permissions
updating: testpkg-1.0.0-hbf21a9e_0.tar.bz2
Nothing to test for: /home/gabm/miniconda3/conda-bld/linux-64/testpkg-1.0.0-hbf21a9e_0.tar.bz2
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /home/gabm/miniconda3/conda-bld/linux-64/testpkg-1.0.0-hbf21a9e_0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []



####################################################################################
Source and build intermediates have been left in /home/gabm/miniconda3/conda-bld.
There are currently 85 accumulated.
To remove them, you can run the ```conda build purge``` command
```

while in 2.1.17 it says:

```
 gabm@pc-klosi /t/test  $ conda build . --skip-existing
updating index in: /home/gabm/miniconda3/conda-bld/linux-64
updating index in: /home/gabm/miniconda3/conda-bld/noarch
Fetching package metadata .................
testpkg-1.0.0-0 is already built in ['local'], skipping.
INFO:conda_build.config:--dirty flag and --keep-old-work not specified.Removing build/test folder after successful build/test.

# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:


# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []



####################################################################################
Source and build intermediates have been left in /home/gabm/miniconda3/conda-bld.
There are currently 85 accumulated.
To remove them, you can run the ```conda build purge``` command
```


I simulated it with local, but in our real usecase its a package in a remote repo - same effect

**Comment by msarahan** [comment]
OK, thanks.  That's basically what our test is, so something is wrong there.  I'll look into it.

**Comment by gabm** [comment]
I'm sorry @msarahan but this still doesn't work in 3.0.5.. I am not using --croot, just a plain `conda build testpkg --skip-existing` fails...

I just reproduced with a clean install using the latest installer and conda-build in 2.1.17 and 3.0.5.


### 2.1.17
```
root@918c47b21c2d:~/testpkg# rm -rf ~/miniconda3/conda-bld/linux-64/* && conda index ~/miniconda3/conda-bld/linux-64/*
updating index in: /root/miniconda3/conda-bld/linux-64/*


root@918c47b21c2d:~/testpkg# conda install conda-build=2.1.17                                                         
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /root/miniconda3:
#
conda-build               2.1.17                   py36_0  


root@918c47b21c2d:~/testpkg# conda build . --skip-existing
updating index in: /root/miniconda3/conda-bld/linux-64
removing: testpkg-1.0.0-hbf21a9e_0.tar.bz2
removing: testpkg-1.0.0-0.tar.bz2
updating index in: /root/miniconda3/conda-bld/noarch
Fetching package metadata ...........
BUILD START: testpkg-1.0.0-0
Package: testpkg-1.0.0-0
source tree in: /root/miniconda3/conda-bld/testpkg_1500024261080/work
INFO:conda_build.build:Packaging testpkg-1.0.0-0
number of files: 0
Fixing permissions
Fixing permissions
/root/miniconda3/conda-bld/linux-64/testpkg-1.0.0-0.tar.bz2
updating index in: /root/miniconda3/conda-bld
updating index in: /root/miniconda3/conda-bld/noarch
updating index in: /root/miniconda3/conda-bld/linux-64
updating: testpkg-1.0.0-0.tar.bz2
updating index in: /root/miniconda3/conda-bld
Nothing to test for: /root/miniconda3/conda-bld/linux-64/testpkg-1.0.0-0.tar.bz2
INFO:conda_build.config:--dirty flag and --keep-old-work not specified.Removing build/test folder after successful build/test.

# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /root/miniconda3/conda-bld/linux-64/testpkg-1.0.0-0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []


root@918c47b21c2d:~/testpkg# conda build . --skip-existing
updating index in: /root/miniconda3/conda-bld/linux-64
updating index in: /root/miniconda3/conda-bld/noarch
Fetching package metadata ...........
testpkg-1.0.0-0 is already built in ['local'], skipping.
INFO:conda_build.config:--dirty flag and --keep-old-work not specified.Removing build/test folder after successful build/test.

# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:


# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
```

### 3.0.5

```
root@918c47b21c2d:~/testpkg# rm -rf ~/miniconda3/conda-bld/linux-64/* && conda index ~/miniconda3/conda-bld/linux-64/*
updating index in: /root/miniconda3/conda-bld/linux-64/*


root@918c47b21c2d:~/testpkg# conda install conda-build=3.0.5                                                          
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /root/miniconda3:

The following packages will be UPDATED:

    conda-build: 2.1.17-py36_0 --> 3.0.5-py36_0

Proceed ([y]/n)? 

conda-build-3. 100% |####################################################################################################################################################################| Time: 0:00:00   1.33 MB/s


root@918c47b21c2d:~/testpkg# conda build . --skip-existing
removing: testpkg-1.0.0-0.tar.bz2
source tree in: /root/miniconda3/conda-bld/testpkg_1500024308722/work
Attempting to finalize metadata for testpkg
INFO:conda_build.metadata:Attempting to finalize metadata for testpkg
BUILD START: ['testpkg-1.0.0-hbf21a9e_0.tar.bz2']
Packaging testpkg
INFO:conda_build.build:Packaging testpkg
Packaging testpkg-1.0.0-hbf21a9e_0
INFO:conda_build.build:Packaging testpkg-1.0.0-hbf21a9e_0
number of files: 0
Fixing permissions
Fixing permissions
updating: testpkg-1.0.0-hbf21a9e_0.tar.bz2
Nothing to test for: /root/miniconda3/conda-bld/linux-64/testpkg-1.0.0-hbf21a9e_0.tar.bz2
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /root/miniconda3/conda-bld/linux-64/testpkg-1.0.0-hbf21a9e_0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []


root@918c47b21c2d:~/testpkg# conda build . --skip-existing
source tree in: /root/miniconda3/conda-bld/testpkg_1500024313371/work
Attempting to finalize metadata for testpkg
INFO:conda_build.metadata:Attempting to finalize metadata for testpkg
BUILD START: ['testpkg-1.0.0-hbf21a9e_0.tar.bz2']
Packaging testpkg
INFO:conda_build.build:Packaging testpkg
Packaging testpkg-1.0.0-hbf21a9e_0
INFO:conda_build.build:Packaging testpkg-1.0.0-hbf21a9e_0
number of files: 0
Fixing permissions
Fixing permissions
updating: testpkg-1.0.0-hbf21a9e_0.tar.bz2
Nothing to test for: /root/miniconda3/conda-bld/linux-64/testpkg-1.0.0-hbf21a9e_0.tar.bz2
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /root/miniconda3/conda-bld/linux-64/testpkg-1.0.0-hbf21a9e_0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
```

**Comment by msarahan** [comment]
Should be fixed by #2200.  The "test" I added wasn't much of a test because the actual test part was commented incorrectly from clumsy copy/paste.  I fixed it and added a separate test to make sure that this also works with --croot.

**Comment by gabm** [comment]
thank you so much for your efforts, I can confirm it works now!

**Comment by gabm** [comment]
sorry @msarahan :/ It works for "local" but not for remote repositories now... that means unfortunately its not fixed yet :(

**Comment by msarahan** [comment]
Please post a test procedure or submit a PR with a test. I can fix it from
there. Sorry to ask for that, but I have to many things to do right now.

**Comment by gabm** [comment]
@msarahan I see whats going on...

the metadata.dist() format changed and the same packages are not recognized as "the same packages" anymore :/

in conda-build 2.* the format was:

```python
# metadata.dist() in is_package_built
'eigen3-3.2.9-3'
```

in conda-build 3.* it is now:

```python
# metadata.dist() in is_package_built
'eigen3-3.2.9-hf07fd11_3'
```

So it includes a hash. I wonder where this hash comes from? its built from source. I tried some popular hashes on the source zip but i couldn't find any matching? The recipe is:

```
package:
  name: eigen3
  version: "3.2.9"

source:
  fn: eigen3-3.2.9.tar.gz
  url: http://bitbucket.org/eigen/eigen/get/3.2.9.tar.bz2
  sha1: 59ab81212f8eb2534b1545a9b42c38bf618a0d71
```

**Comment by gabm** [comment]
Ok, I see the hash is a hash of the recipe, is that true?

**Comment by msarahan** [comment]
Thanks for isolating the issue.

docs for exactly what goes into a hash are at https://conda.io/docs/building/variants.html#differentiating-packages-built-with-different-variants

You can disable hashes with ``--old-build-string``, but conda-build will not warn you about recipes with variants that clobber each other.

We probably need to document that --skip-existing only skips packages with identical filenames, and that packages built without hashes won't get picked up by CB3 by default.
